### ISSUE TITLE
Let the user know to use /r to reply on first DM of that connection

### ISSUE THREAD

**Issue by cyberkitsune** [cyberkitsune/KitsuneChat#12]
We should let the user know that they can reply to their DM with /r

**Comment by sournub** [comment]
to show user they can /r every time they get a /msg
but only on the first /msg every time they join the server
resets the reminder when they leave and join the server again
have command that doesnt show the reminder ever for user

**Comment by cyberkitsune** [comment]
Tasks needed for this issue:

- [ ] Create a `List` of users in UserMessaging
- [ ] Once a user gets a message, if they are not in the list, add them and warn about using `/r`
- [ ] Add a Disconnect listener for UserMessaging, remove player from list on disconnect if they're in it

Command will be more complex, make separate issue for it.
