### ISSUE TITLE
Using /r prints an error message.

### ISSUE THREAD

**Issue by alekso56** [cyberkitsune/KitsuneChat#9]
The error message is '[KitsuneChat] I can't find (first argument from /r here)! D:'

and /me doesn't work.

**Comment by TerrorBite** [comment]
I'll have a look into this, it's about time KitsuneChat got some TLC from a developer.

When you say "/me doesn't work", can you give some more details?

**Comment by alekso56** [comment]
It errors with the same message, i think the plugin fails to get a proper list of players. :+1:

**Comment by cyberkitsune** [comment]
Looks like this actually had to do with nicknames, funny.

Fixed as of https://github.com/cyberkitsune/KitsuneChat/commit/a728ebeed42399d8526571bd007652ff84dfb29e

**Comment by alekso56** [comment]
Thanks for the fast response.  ⭐
